### ISSUE TITLE
onMessage does not work anymore.

### ISSUE THREAD

**Issue by ccfiel** [tulir/fbchat-asyncio#1]
onMessage is not trigger anymore. 

https://github.com/carpedm20/fbchat/issues/483
https://github.com/Schmavery/facebook-chat-api/issues/763

any solutions?

**Comment by tulir** [comment]
As per https://github.com/carpedm20/fbchat/issues/483#issuecomment-556337226, my [yet-another-rewrite](https://github.com/tulir/fbchat-asyncio/tree/yet-another-rewrite) branch implements the MQTT websocket connection. I'll merge it into master after cleaning it up a bit, but it should already work (multiple people confirmed my [matrix-facebook bridge](https://github.com/tulir/mautrix-facebook/tree/update-fbchat) works when using that branch)

**Comment by tulir** [comment]
Cleaned up the code now. It's on the master branch and published to PyPI as fbchat-asyncio 0.3.0b2: https://pypi.org/project/fbchat-asyncio/0.3.0b2/

**Comment by jvfiel** [comment]
Thank you @tulir, I did pip install fbchat-asyncio==0.3.0b2  but still not working on my end. Yesterday https://github.com/tulir/fbchat-asyncio/tree/yet-another-rewrite was working, now when I tried yet-another-rewrite branch again not working anymore.
