### ISSUE TITLE
The client no longer receives the message after a period of listening

### ISSUE THREAD

**Issue by 28dec** [tulir/fbchat-asyncio#16]
I'm facing a problem that my bot keep listen 24/24, when i start the script, it worked perfectly but after a period of time (few hours, may be), it still running, however when someone send a message, it do not received any thing.
Can someone please tell me what i am wrong?

**Comment by mockshox** [comment]
Same did happen for me. I ended up scheduling process restart to avoid it.

**Comment by 28dec** [comment]
original fbchat working now! so I decided to transfer back my project to it!
