### ISSUE TITLE
Related to fbchat-asyncio==0.3.0b2

### ISSUE THREAD

**Issue by jvfiel** [tulir/fbchat-asyncio#2]
I pip install fbchat-asyncio==0.3.0b2 and still the it's not listening.

**Comment by jvfiel** [comment]
related to https://github.com/tulir/fbchat-asyncio/issues/1

**Comment by tulir** [comment]
Try fbchat-asyncio==0.3.0b6. If that doesn't work, enable debug logging for `hbmqtt` and `websockets` to see what's happening exactly

**Comment by jvfiel** [comment]
Ok will try

**Comment by jvfiel** [comment]
still not listening. I will try to enable logging.

**Comment by jvfiel** [comment]
it seems that the package is fine, I think the code sample we are using is not working anymore. Is there an updated code sample also? @jvfiel

**Comment by HossamMohsen7** [comment]
See closed issue #5.
```onMessage``` is now ```on_message```
