### ISSUE TITLE
Can't run any code

### ISSUE THREAD

**Issue by Dnick421** [tulir/fbchat-asyncio#24]
![s3](https://user-images.githubusercontent.com/73164309/96719312-85cae700-13a9-11eb-8328-ca6d0ee4d584.png)

Traceback (most recent call last):
  File "C:/Users/én/Desktop/fbchat-asyncio/examples/basic_usage.py", line 6, in <module>
    print("Own id: {}".format(session.user.id))
AttributeError: 'coroutine' object has no attribute 'user'
sys:1: RuntimeWarning: coroutine 'Session.login' was never awaited
![s4](https://user-images.githubusercontent.com/73164309/96720092-a0519000-13aa-11eb-8d40-8d9b192a3590.png)

**Comment by tulir** [comment]
The examples aren't up to date, but adding `await` to all the relevant places might make them work

**Comment by NORXND** [comment]
> The examples aren't up to date, but adding `await` to all the relevant places might make them work

Not only that. @tulir 
``` py
Traceback (most recent call last):
  File "D:/PyCharm/Projects/Edu/messenger_platform/main.py", line 6, in <module>
    print("Own id: {}".format(session.user.id))
AttributeError: 'coroutine' object has no attribute 'user'
sys:1: RuntimeWarning: coroutine 'Session.login' was never awaited
```
But anyway, something is wrong with `await session.logout()`. Exception: 
``` py
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000024484B6BC10>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000024484B67E80>, 612877.843)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000024484B6BB80>
``` 
I'm sure it's raised by logout.

**Comment by tulir** [comment]
The first error is saying you didn't await and the second error isn't raised by logout.
