### ISSUE TITLE
Examples with asyncio

### ISSUE THREAD

**Issue by HossamMohsen7** [tulir/fbchat-asyncio#3]
## Description
There's no examples with asyncio used.

**Comment by ccfiel** [comment]
@7osCraft I made a pr waiting to be merge. Here is the sample code but same thing it does not listen :(

```
# -*- coding: UTF-8 -*-
from fbchat import Client
import asyncio


# Subclass fbchat.Client and override required methods
class EchoBot(Client):
    async def onMessage(self, author_id, message_object, thread_id, thread_type, **kwargs):
        await self.markAsDelivered(thread_id, message_object.uid)
        await self.markAsRead(thread_id)

        log.info("{} from {} in {}".format(message_object, thread_id, thread_type.name))
        print(message_object)
        # If you're not the author, echo
        if author_id != self.uid:
            await self.send(message_object, thread_id=thread_id, thread_type=thread_type)

async def start():
    client = EchoBot()
    print("start..")
    await client.start("abrown.brooky2@gmail.com", "brooky123456")
    client.listen()

asyncio.get_event_loop().run_until_complete(start())
asyncio.get_event_loop().run_forever()
```

**Comment by ccfiel** [comment]
@7osCraft I tried to enable logging. Message is flowing but the onMessage is not trigger. I think @tulir has a new listener function for his package.

**Comment by ccfiel** [comment]
@7osCraft this is the correct sample code. I also made a PR https://github.com/tulir/fbchat-asyncio/pull/6

```
# -*- coding: UTF-8 -*-
from fbchat import Client
import asyncio

# Subclass fbchat.Client and override required methods
class EchoBot(Client):
    async def on_message(self, author_id, message_object, thread_id, thread_type, **kwargs):
        await self.mark_as_delivered(thread_id, message_object.uid)
        await self.mark_as_read(thread_id)

        # If you're not the author, echo
        if author_id != self.uid:
            await self.send(message_object, thread_id=thread_id, thread_type=thread_type)

async def start():
    client = EchoBot()
    print("start..")
    await client.start("<email>", "<password>")
    client.listen()


asyncio.get_event_loop().run_until_complete(start())
asyncio.get_event_loop().run_forever()

```

**Comment by HossamMohsen7** [comment]
Thank you

**Comment by jvfiel** [comment]
have you tried sending files?

mine is giving error

/lib/python3.6/site-packages/fbchat/_client.py:2866: RuntimeWarning: coroutine 'get_files_from_urls' was never awaited

Here's my code

        await self.send_remote_files(images_,
                                                 message=Message(text=text, mentions=mentions),
                                                 thread_id=thread_id,
                                                 thread_type=thread_type)

**Comment by jvfiel** [comment]
have you experienced this https://github.com/tulir/fbchat-asyncio/issues/7 @7osCraft ?

**Comment by HossamMohsen7** [comment]
@jvfiel Didn't try that. But I will try in my free time.

**Comment by tulir** [comment]
All the examples are now converted to asyncio, although I didn't test them. Please create new issues or pull requests if the examples are broken

@jvfiel `send_remote_*` methods were missing some awaits internally, added them now.
