### ISSUE TITLE
onMessage is not working but its logging the message

### ISSUE THREAD

**Issue by ccfiel** [tulir/fbchat-asyncio#5]
I enable logging. Message is coming in but the onMessage is not trigger is there any new event for incoming messages for this package?

```
# -*- coding: UTF-8 -*-
from fbchat import Client
import asyncio


# Subclass fbchat.Client and override required methods
class EchoBot(Client):
    async def onMessage(self, author_id, message_object, thread_id, thread_type, **kwargs):
        await self.markAsDelivered(thread_id, message_object.uid)
        await self.markAsRead(thread_id)

        log.info("{} from {} in {}".format(message_object, thread_id, thread_type.name))
        print(message_object)
        # If you're not the author, echo
        if author_id != self.uid:
            await self.send(message_object, thread_id=thread_id, thread_type=thread_type)

async def start():
    client = EchoBot()
    print("start..")
    await client.start("<email>", "<password>")
    client.listen()

asyncio.get_event_loop().run_until_complete(start())
asyncio.get_event_loop().run_forever()
```

**Comment by ccfiel** [comment]
ok I have solve the problem :)

```
# -*- coding: UTF-8 -*-
from fbchat import Client
import asyncio

# Subclass fbchat.Client and override required methods
class EchoBot(Client):
    async def on_message(self, author_id, message_object, thread_id, thread_type, **kwargs):
        await self.mark_as_delivered(thread_id, message_object.uid)
        await self.mark_as_read(thread_id)

        # If you're not the author, echo
        if author_id != self.uid:
            await self.send(message_object, thread_id=thread_id, thread_type=thread_type)

async def start():
    client = EchoBot()
    print("start..")
    await client.start("abrown.brooky2@gmail.com", "brooky123456")
    client.listen()


asyncio.get_event_loop().run_until_complete(start())
asyncio.get_event_loop().run_forever()
```

**Comment by Phalelashvili** [comment]
> 
> 
> ok I have solve the problem :)
> 
> ```
> # -*- coding: UTF-8 -*-
> from fbchat import Client
> import asyncio
> 
> # Subclass fbchat.Client and override required methods
> class EchoBot(Client):
>     async def on_message(self, author_id, message_object, thread_id, thread_type, **kwargs):
>         await self.mark_as_delivered(thread_id, message_object.uid)
>         await self.mark_as_read(thread_id)
> 
>         # If you're not the author, echo
>         if author_id != self.uid:
>             await self.send(message_object, thread_id=thread_id, thread_type=thread_type)
> 
> async def start():
>     client = EchoBot()
>     print("start..")
>     await client.start("abrown.brooky2@gmail.com", "brooky123456")
>     client.listen()
> 
> 
> asyncio.get_event_loop().run_until_complete(start())
> asyncio.get_event_loop().run_forever()
> ```

did you just reveal your facebook credentials

**Comment by ccfiel** [comment]
@Phalelashvili its just a dummy account no worries

**Comment by Phalelashvili** [comment]
if someone else is having same problem and updated code doesn't fix it, don't install old version from pip or you'll still face error with this code, install it from github.
