### ISSUE TITLE
AttributeError: 'str' object has no attribute 'getChild'

### ISSUE THREAD

**Issue by karaolidis** [tulir/fbchat-asyncio#8]
## Description of the problem
No matter what I try, I can't seem to be able to log in to my messenger account. I get the following error every time:

## Code to reproduce
```py
from fbchat import Client
from fbchat.models import *

client = Client("[...]")

print("Own id: {}".format(client.uid))
client.send(Message(text="Hi me!"), thread_id=client.uid, thread_type=ThreadType.USER)

client.logout()
```

## Traceback
```
Traceback (most recent call last):
  File "d:/Documents/_Projects/Python/Admina/FBBotV5/test.py", line 4, in <module>
    client = Client("[...]")
  File "d:\Documents\_Projects\Python\Admina\FBBotV5\venv\lib\site-packages\fbchat\_client.py", line 72, in __init__
    self._log = self._base_log.getChild("client")
AttributeError: 'str' object has no attribute 'getChild'
```

## Environment information
- Python version: 3.7.4

**Comment by tulir** [comment]
The examples were the original examples from fbchat. I've updated them now for asyncio, although I didn't test them. Try the new [examples/basic_usage.py](https://github.com/tulir/fbchat-asyncio/blob/master/examples/basic_usage.py)

**Comment by karaolidis** [comment]
Thanks, this worked!
